language: android
sudo: false

env:
  - TZ=Europe/Berlin

install:
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch --unshallow --tags

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - build-tools-29.0.2
    - build-tools-29.0.3
    - android-24
    - android-28
    - android-29
    - extra
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-24

# Emulator Management: Create, Start and Wait
before_script:
  - android list targets
  - echo no | android create avd --force -n test --target android-24 --abi armeabi-v7a
  - QEMU_AUDIO_DRV=none emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - android list target
  - ./gradlew check connectedAndroidTest

after_script:
  - cat /home/travis/build/dmfs/opentasks/opentasks/build/reports/lint-results.xml
